import {controlLibrary,equipmentTypes} from '../data/controlLibrary.js';
import {SelectField,TextArea} from './Field.jsx';
const MAX=5;
function Multi({title,options,selected,onChange}){function toggle(o){if(selected.includes(o))onChange(selected.filter(x=>x!==o));else if(selected.length<MAX)onChange([...selected,o]);}
return <div><label>{title} <span className="small">Select up to {MAX}</span></label><ol className="selectedList">{selected.map(x=><li key={x}>{x}</li>)}</ol><div className="picker">{options.map(o=>{const disabled=!selected.includes(o)&&selected.length>=MAX;return <label key={o} className={disabled?'disabled':''}><input type="checkbox" checked={selected.includes(o)} disabled={disabled} onChange={()=>toggle(o)}/>{o}</label>})}</div></div>}
export default function ControlPicker({data,setData}){const cards=data.hazardCards||[];const selectedHazards=data.hazards||[];function ensureCards(){const map=new Map(cards.map(c=>[c.hazard,c]));return selectedHazards.map(h=>map.get(h)||{hazard:h,equipmentType:'',source:'',direct:[],indirect:[],site:[],directVerified:[],indirectVerified:[],siteVerified:[]});}
const synced=ensureCards();if(JSON.stringify(cards.map(c=>c.hazard))!==JSON.stringify(synced.map(c=>c.hazard)))setTimeout(()=>setData({...data,hazardCards:synced}),0);
function update(i,patch){const next=[...synced];next[i]={...next[i],...patch};setData({...data,hazardCards:next});}
function toggleVerified(i,group,control){const key=group+'Verified';const arr=synced[i][key]||[];update(i,{[key]:arr.includes(control)?arr.filter(x=>x!==control):[...arr,control]});}
return <section className="card"><h2>Work Front Hazard Review & Critical Control Verification</h2><p className="sub">Controls are driven by the selected High Energy Hazard. Hazard Source is entered manually to identify the exact source/location being controlled.</p>{synced.length===0&&<p className="small">Select High Energy Hazards above to generate control cards.</p>}{synced.map((c,i)=>{const lib=controlLibrary[c.hazard]||controlLibrary.Other;return <div className="controlCard" key={c.hazard}><h3>{c.hazard}</h3><div className="grid"><SelectField label="Equipment Type" value={c.equipmentType} onChange={v=>update(i,{equipmentType:v})} options={equipmentTypes}/><TextArea label="Hazard Source" value={c.source} onChange={v=>update(i,{source:v})}/></div><div className="controlGrid"><Multi title="Direct Controls" options={lib.direct} selected={c.direct||[]} onChange={v=>update(i,{direct:v,directVerified:(c.directVerified||[]).filter(x=>v.includes(x))})}/><Multi title="Indirect Controls" options={lib.indirect} selected={c.indirect||[]} onChange={v=>update(i,{indirect:v,indirectVerified:(c.indirectVerified||[]).filter(x=>v.includes(x))})}/><Multi title="Additional / Site-Specific Controls" options={lib.site} selected={c.site||[]} onChange={v=>update(i,{site:v,siteVerified:(c.siteVerified||[]).filter(x=>v.includes(x))})}/></div><div className="row"><label>Verified Controls</label><div className="controlGrid"><div>{(c.direct||[]).map(x=><label key={x}><input type="checkbox" checked={(c.directVerified||[]).includes(x)} onChange={()=>toggleVerified(i,'direct',x)}/> {x}</label>)}</div><div>{(c.indirect||[]).map(x=><label key={x}><input type="checkbox" checked={(c.indirectVerified||[]).includes(x)} onChange={()=>toggleVerified(i,'indirect',x)}/> {x}</label>)}</div><div>{(c.site||[]).map(x=><label key={x}><input type="checkbox" checked={(c.siteVerified||[]).includes(x)} onChange={()=>toggleVerified(i,'site',x)}/> {x}</label>)}</div></div></div></div>})}</section>}
